#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d I II III
bspc monitor HDMI-1 -d I II III IV V

# bsp config
bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a URxvt state=floating

$HOME/.config/polybar/launch.sh
